---
extends: default
ignore: |
  meta
  venv
  .travis/
  .travis.yml

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
