---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- block:
    - name: Get latest Cortex release
      uri:
        url: https://api.github.com/repos/cortexproject/cortex/releases/latest
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      # no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: Set cortex_version to {{ _latest_release.json.tag_name[1:] }} (latest)
      set_fact:
        cortex_version: "{{ _latest_release.json.tag_name[1:] }}"
        cortex_checksum: |
          {{ lookup('url',
             'https://github.com/cortexproject/cortex/releases/download/v' + _latest_release.json.tag_name[1:] + '/cortex-linux-amd64-sha-256')
          }}
  when:
    - cortex_version == "latest"
