---
- name: Set up object storage
  hosts: minio
  tasks:
    - file: path=/data/metrics-enterprise-admin state=directory

- name: Converge
  hosts: metrics-enterprise
  tasks:
    - name: Include ansible-cortex
      include_role:
        name: ansible-cortex
      vars:
        enterprise: true
        metrics_enterprise_cluster_name: test
        metrics_enterprise_license_file: license.jwt
        config_template: metrics-enterprise-cluster.yml.j2
