---
- name: Restart service
  shell:
    cmd: "systemctl daemon-reload && systemctl restart {{ name }}"
# TODO: understand why this isn't working in the platform containers
#   systemd:
#     daemon_reload: true
#     name: "{{ name }}"
#     state: restarted
