---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test server /ready endpoint"
      uri:
        url: "http://127.0.0.1:80/ready"
        return_content: true
      register: this
